version: '3.8'

services:
  janus:
    build:
      context: .
      dockerfile: Dockerfile
      target: build  # Stop at build stage for development
    image: swmansion/janus-gateway:1.3.2-0-dev
    container_name: janus-gateway-dev
    command: /bin/bash  # Keep container running for debugging
    volumes:
      - .:/workspace
      - /workspace/build  # Exclude build directory
    working_dir: /workspace
    environment:
      - DEBUG_LEVEL=7
      - DEBUG_COLORS=true
    networks:
      - janus-dev-network

  # Optional: RabbitMQ for message queuing
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: janus-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=janus
      - RABBITMQ_DEFAULT_PASS=janus123
      - RABBITMQ_DEFAULT_VHOST=janus
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - janus-dev-network

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: janus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - janus-dev-network

  # Optional: Nginx for reverse proxy
  nginx:
    image: nginx:alpine
    container_name: janus-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - janus
    networks:
      - janus-dev-network

volumes:
  rabbitmq_data:
  redis_data:

networks:
  janus-dev-network:
    driver: bridge