apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: janus-gateway

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- networkpolicy.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: janus-gateway
  app.kubernetes.io/component: webrtc-gateway
  app.kubernetes.io/version: "1.3.2"

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: janus-gateway
  spec:
    template:
      spec:
        volumes:
        - name: recordings
          persistentVolumeClaim:
            claimName: janus-recordings-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: janus-logs-pvc