apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: janus-recordings-pvc
  namespace: janus-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: janus-logs-pvc
  namespace: janus-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard